spring:
  application:
    name: LeatherGoodsStore
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
  liquibase:
    change-log: db/changelog/changelog-master.xml
  mvc:
    hiddenmethod:
      filter:
        enabled: true

path:
  to:
    images:
      for:
        slides: /store/images/slides
        posts: /store/images/posts