spring:
  application:
    name: LeatherGoodsStore
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: db/changelog/changelog-master.xml
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

path:
  to:
    images:
      for:
        slides: /store/images/slides
        posts: /store/images/posts
        leathers: /store/images/leathers
        leathers-colors: /store/images/leathers_colors
        products: /store/images/products
        products-leather-colors: /store/images/products_leather_colors

credentials:
  yookassa:
    shop-id:
    secret-key:
  dadata:
    token: